// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yandsyqvpgfixprebnob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhbmRzeXF2cGdmaXhwcmVibm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTY1MDAsImV4cCI6MjA2NDk3MjUwMH0.BdX34M1fo1wfQQg1bLjDti6P-GnHYDVQtonLjwHnuw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);